name: CI Pipeline

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install
      - name: Move to server 
        run: |
            echo "$EC2_KEY" | base64 --decode > /tmp/deploy-key.pem
            - chmod 400 /tmp/deploy-key.pem
            - mkdir -p ~/.ssh
            - ssh-keyscan -H <> >> ~/.ssh/known_hosts

            - ssh -i /tmp/deploy-key.pem ec2-user@<> << 'EOF'
                sudo mkdir -p /var/www/directory/
                sudo chmod -R 755 /var/www/directory/
              EOF

            - scp -i /tmp/deploy-key.pem -r * ec2-user@<>:/tmp/

            - ssh -i /tmp/deploy-key.pem ec2-user@<> << 'EOF'
                sudo mv /tmp/* /var/www/directory/
                sudo systemctl restart nginx
                sudo pm2 restart <app-name>
              EOF
            - rm -f /tmp/deploy-key.pem
